site_name: Codeball v0.4.0
site_url: https://codeball.metrica-sports.com
repo_url: https://github.com/metrica-sports/codeball
repo_name: 'Codeball'
edit_uri: blob/master/docs/

theme:
  name: material
  palette:
    primary: teal

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True

nav:
    - Home: index.md
    - GameDataset: game-dataset.md
    - CodeballFrames: codeball-frames.md
    - Patterns: patterns.md
    - Tactical: tactical.md
    - Metrica Play API: 
      - What you can do: metrica-play-api.md
      - File Formatting: format-for-play.md
      - Visualizations: visualizations.md
      - How to import a file: how-to-import-to-play.md
    - Examples:
      - GameDataset: examples/game_dataset.ipynb
      - Example pattern: examples/example-pattern.md
      - Run patterns: examples/run_patterns.ipynb
    - Changelog: changelog.md
      
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: table

